version: 1.0.{build}

image: Visual Studio 2017

configuration: Release

platform: Any CPU

before_build:
  - ps: nuget restore OpenHardwareMonitor.sln
  
build:
  project: OpenHardwareMonitor.sln
  verbosity: minimal

deploy:
  provider: GitHub
  auth_token:
    secure: CFX0npfCcVQxG4zzXNhUkB8mfhfyFDNiBp7m66sPRq4fIXdZeSM08pTVFjVw9LcH
  artifact: /.*\.zip/
  on:
    branch: master
  
# artifacts:
  # - path: 'Bin\Release\'
